### ISSUE TITLE
Requesting help to resolve an error encountered while running code

### ISSUE THREAD

**Issue by cuiyaxuan** [yuqiuzhou/Pianno#4]
Could you please help me? When I run the code according to the example, it always reports the following error. How should I resolve it?

 adata = po.AutoPatternRecognition(adata,
...                                   Patterndict=Patterndict,
...                                   config_path=config_path,
...                                   param_tuning=True,
...                                   max_experiment_duration='10m')

[2024-08-09 14:28:04] Creating experiment, Experiment ID: e5i9u3rk
[2024-08-09 14:28:04] Starting web server...
[2024-08-09 14:28:06] Setting up...
[2024-08-09 14:28:06] Web portal URLs: http://127.0.0.1:8080 http://192.168.100.25:8080 http://172.17.0.1:8080
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda3/envs/Pianno/lib/python3.9/site-packages/pianno/_auto_pattern_recognition.py", line 55, in AutoPatternRecognition
    best_params = SearchBestParams(adata,
  File "/home/anaconda3/envs/Pianno/lib/python3.9/site-packages/pianno/_search_best_params.py", line 72, in SearchBestParams
    return best_params[list(best_params.keys())[0]]
IndexError: list index out of range
>>>

**Comment by yuqiuzhou** [comment]
It seems that the NNI toolkit doesn't work normally. Is there an empty "best_params.json" file generated under your "config_path"？Please open the portal URL to check if the tuning went well first.  Each experiment log can be found in "/home/anaconda3/envs/Pianno/lib/python3.9/site-packages/pianno/nni_experiment". Could you please provide the error message? If "nni_experiment" doesn't exist, open the "pianno/_tuner.py" to comment out the last line ("shutil.rmtree(ewd)") and run again.

**Comment by cuiyaxuan** [comment]
Thank you for your reply. I tried again but still encountered the following error. The 'best_params.json' file can be generated in the 'config_path,' and the nni_experiment folder was also created in my user directory, but it wasn't created under the pianno folder. I installed the pianno package via pip, and the following ima
![WX20240813-192806@2x](https://github.com/user-attachments/assets/eeacebdf-a715-4a2d-8357-41a7c00b15fa)
![WX20240813-192711@2x](https://github.com/user-attachments/assets/087c730c-721f-443e-a6da-d70412b5cca2)
![WX20240813-192643@2x](https://github.com/user-attachments/assets/5618559e-74e5-45eb-9262-101f7cac3154)
ge provides specific information.

**Comment by yuqiuzhou** [comment]
Well, have you checked the portal URL of NNI? Is the "best_params.json" empty? Is there any error message saved in the "nni-experiment"? Could you please share these contents with me?

**Comment by yuqiuzhou** [comment]
Something is wrong with the NNI toolkit. We need the experiment log (a file named by the experiment ID, e.g. "e5i9u3rk") to find out. Thanks for your time.

**Comment by cuiyaxuan** [comment]
![WX20240818-102023@2x](https://github.com/user-attachments/assets/aa3fcbcc-19ff-4321-8579-8183fc1779c8)
[GT151673.zip](https://github.com/user-attachments/files/16646913/GT151673.zip)
[nni-experiments.zip](https://github.com/user-attachments/files/16646914/nni-experiments.zip)
![WX20240818-101858](https://github.com/user-attachments/assets/56e066b1-6535-4e28-9d8f-f87d3949d298)

Thank you for your response. I just reran the code, and here are some of the data and results produced. The best_params.json file is empty.

**Comment by yuqiuzhou** [comment]
Be sure that you have removed the "best_params.json" before a new experiment. Can you open the "http://127.0.0.1:8080/" while running?

**Comment by cuiyaxuan** [comment]
Unable to open this link: "http://127.0.0.1:8080/". Additionally, every time I run it, the IP port gets occupied, and I have to manually kill the process.
![WX20240818-104516@2x](https://github.com/user-attachments/assets/8032331e-6976-421a-9f49-0a3e8459cb12)

**Comment by lylyly785** [comment]
I have also found this problem. Is there any solution now?

**Comment by cuiyaxuan** [comment]
The code issue has not been resolved yet.

**Comment by XiangyuLi-Lab** [comment]
I also encountered the same problem, is this problem solved now?
